//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace WorkerServicesDemo.Data.HelperClasses
{
	/// <summary>Field Creation Class for entity DemoEntity</summary>
	public partial class DemoFields
	{
		/// <summary>Creates a new DemoEntity.DateCreated field instance</summary>
		public static EntityField2 DateCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DemoFieldIndex.DateCreated); }}
		/// <summary>Creates a new DemoEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DemoFieldIndex.Id); }}
		/// <summary>Creates a new DemoEntity.LastModified field instance</summary>
		public static EntityField2 LastModified { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DemoFieldIndex.LastModified); }}
		/// <summary>Creates a new DemoEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DemoFieldIndex.Value); }}
	}
	

}