//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WorkerServicesDemo.Data.HelperClasses;
using WorkerServicesDemo.Data.FactoryClasses;
using WorkerServicesDemo.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace WorkerServicesDemo.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Demo'.<br/><br/></summary>
	[Serializable]
	public partial class DemoEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static DemoEntityStaticMetaData _staticMetaData = new DemoEntityStaticMetaData();
		private static DemoRelations _relationsFactory = new DemoRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DemoEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DemoEntityStaticMetaData()
			{
				SetEntityCoreInfo("DemoEntity", InheritanceHierarchyType.None, false, (int)WorkerServicesDemo.Data.EntityType.DemoEntity, typeof(DemoEntity), typeof(DemoEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static DemoEntity()
		{
		}

		/// <summary> CTor</summary>
		public DemoEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DemoEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DemoEntity</param>
		public DemoEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Demo which data should be fetched into this Demo object</param>
		public DemoEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Demo which data should be fetched into this Demo object</param>
		/// <param name="validator">The custom validator object for this DemoEntity</param>
		public DemoEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DemoEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DemoEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DemoRelations Relations { get { return _relationsFactory; } }

		/// <summary>The DateCreated property of the Entity Demo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Demo"."DateCreated".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime DateCreated
		{
			get { return (System.DateTime)GetValue((int)DemoFieldIndex.DateCreated, true); }
			set	{ SetValue((int)DemoFieldIndex.DateCreated, value); }
		}

		/// <summary>The Id property of the Entity Demo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Demo"."Id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)DemoFieldIndex.Id, true); }
			set { SetValue((int)DemoFieldIndex.Id, value); }		}

		/// <summary>The LastModified property of the Entity Demo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Demo"."LastModified".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime LastModified
		{
			get { return (System.DateTime)GetValue((int)DemoFieldIndex.LastModified, true); }
			set	{ SetValue((int)DemoFieldIndex.LastModified, value); }
		}

		/// <summary>The Value property of the Entity Demo<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Demo"."Value".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Value
		{
			get { return (System.Int32)GetValue((int)DemoFieldIndex.Value, true); }
			set	{ SetValue((int)DemoFieldIndex.Value, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace WorkerServicesDemo.Data
{
	public enum DemoFieldIndex
	{
		///<summary>DateCreated. </summary>
		DateCreated,
		///<summary>Id. </summary>
		Id,
		///<summary>LastModified. </summary>
		LastModified,
		///<summary>Value. </summary>
		Value,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace WorkerServicesDemo.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Demo. </summary>
	public partial class DemoRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDemoRelations
	{

		/// <summary>CTor</summary>
		static StaticDemoRelations() { }
	}
}
